export const URL_AUTH = 'https://unsplash.com/oauth/authorize?';
export const CLIENT_ID = 'OgXYrALCZxILAKMwVntH_YHoGTbxf4gFkRyQ-whLpAc';
export const RESPONSE_TYPE = 'code';
export const REDIRECT_URI = 'http://localhost:3000/';
export const SCOPE = 'public read_user read_photos write_likes';
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token?';
export const GRANT_TYPE = 'authorization_code';
export const URL_API = 'https://api.unsplash.com';
export const CLIENT_SECRET = 'jaCNmPtZ-u3uRzTmaNFD9KsRHND9vdTqXzZUaqTcvNI';